# Generated by Django 5.0.5 on 2024-05-22 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": [
                    "category",
                    "name",
                    "price",
                    "data_make",
                    "data_last_save",
                    "views_counter",
                    "is_published",
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.RenameField(
            model_name="product",
            old_name="views_count",
            new_name="views_counter",
        ),
    ]
