# Generated by Django 5.0.5 on 2024-05-29 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="name_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="catalog.product",
                verbose_name="название продукта",
            ),
        ),
    ]
